---
Name: graphql-devtools
After:
  - 'graphql-dev'
---
SilverStripe\GraphQLDevTools\Controller:
  schemas:
    - default
  default_schema: default

---
Name: devtool-routes
After:
  - 'graphql-dev'
---
SilverStripe\Dev\DevelopmentAdmin:
  commands:
    'graphql/clear': 'SilverStripe\GraphQLDevTools\SchemaClear'
  controllers:
    'graphql/ide':
      class: 'SilverStripe\GraphQLDevTools\Controller'
      description: Run the GraphQL IDE
